minor err msg fix

diff --git a/man2html b/man2html
--- a/man2html
+++ b/man2html
@@ -48,7 +48,7 @@ fi
 pdf2htmlex $dirout/$manpage.pdf $dirout/$manpage.html 
 if [ $? -gt 0 ] ;
 then
-  echo 'ps2pdf' failed error $? ...
+  echo 'pdf2htmlex' failed error $? ...
   exit 1
 else
   rm -f $dirout/$manpage.pdf
